apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers-config
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "PostgreSQL Server",
          "Group": "Servers",
          "Host": "postgres.default.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "changeme",
          "SSLMode": "disable"
        }
      }
    }
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:8.13
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: pgadmin-servers
          mountPath: /pgadmin4/servers.json
          subPath: servers.json
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@example.com # changeme
        - name: PGADMIN_DEFAULT_PASSWORD
          value: changeme
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 70
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 70
          periodSeconds: 5
      volumes:
        - name: pgadmin-servers
          configMap:
            name: pgadmin-servers-config
