apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    # Required
    ##########

    # Set a memory usage limit to the specified amount of bytes.
    # When the memory limit is reached Redis will try to remove keys
    # according to the eviction policy selected (see maxmemory-policy).
    maxmemory 100mb

    # Optional
    ##########

    # Evict any key using approximated LFU when maxmemory is reached.
    maxmemory-policy allkeys-lfu

    # Enable active memory defragmentation.
    activedefrag yes

    # Don't save data on the disk because we can afford to lose cached data.
    save ""

    # Protected Mode
    protected-mode no